language: python
python:
  - "3.6"

install: "make"

addons:
  ssh_known_hosts: 45.63.89.166

script:
  - echo "TODO"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_18b059aa1834_key -iv $encrypted_18b059aa1834_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_rsa
  - ssh-add .travis/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script:
      rsync -r --quiet $TRAVIS_BUILD_DIR/ root@45.63.89.166:~;
      ssh root@207.246.83.219 touch done.txt;
    on:
      branch: master
